/*
 * Flight_Controller.java
 *
 * Created on June 18, 2001, 12:59 PM
 */

package flightController;

import java.io.*;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author  sweep
 * @version
 */
public class Flight_Controller extends javax.swing.JPanel {
    
    private String out_filename;
    private String in_filename;
    
    /** Creates new form Flight_Controller */
    public Flight_Controller( String in_name, String out_name ) {
        initComponents ();
        
        in_filename = in_name;
        out_filename = out_name;
        
        writeAgentControls();
        
        // re-read agent info every 1 millisecond
        new Timer( 1, new ActionListener()
        {
            public void actionPerformed( ActionEvent ae )
            {
                readAgentInfo();
            }
        } ).start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jSlider2 = new javax.swing.JSlider();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        setLayout(null);
        
        jSlider1.setBorder(new javax.swing.border.TitledBorder("Throttle"));
        jSlider1.setMinimumSize(new java.awt.Dimension(50, 36));
        jSlider1.setMinorTickSpacing(25);
        jSlider1.setPaintTicks(true);
        jSlider1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSlider1.setMajorTickSpacing(50);
        jSlider1.setMaximum(300);
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        }
        );
        
        add(jSlider1);
        jSlider1.setBounds(10, 10, 70, 220);
        
        
        jTextField1.setEditable(false);
        jTextField1.setText(Integer.toString( jSlider1.getValue() ));
        jTextField1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        add(jTextField1);
        jTextField1.setBounds(20, 230, 50, 30);
        
        
        jSlider2.setBorder(new javax.swing.border.TitledBorder("Omega"));
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSlider2.setMinimum(-100);
        jSlider2.setMajorTickSpacing(100);
        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        }
        );
        
        add(jSlider2);
        jSlider2.setBounds(90, 10, 70, 220);
        
        
        jTextField2.setEditable(false);
        jTextField2.setText(Float.toString( (float)jSlider2.getValue() / (float)jSlider2.getMaximum() ));
        jTextField2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        add(jTextField2);
        jTextField2.setBounds(100, 230, 50, 30);
        
        
        jTextField3.setBorder(new javax.swing.border.TitledBorder("Velocity"));
        jTextField3.setEditable(false);
        jTextField3.setText("0");
        jTextField3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        add(jTextField3);
        jTextField3.setBounds(170, 10, 100, 60);
        
        
        jTextField4.setBorder(new javax.swing.border.TitledBorder("Theta"));
        jTextField4.setEditable(false);
        jTextField4.setText("0");
        jTextField4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        add(jTextField4);
        jTextField4.setBounds(170, 80, 100, 60);
        
    }//GEN-END:initComponents
    
  private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
      jTextField2.setText(Float.toString( (float)jSlider2.getValue() / (float)jSlider2.getMaximum() ));
      writeAgentControls();
  }//GEN-LAST:event_jSlider2StateChanged
  
  private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
      jTextField1.setText( Integer.toString( jSlider1.getValue() ) );
      writeAgentControls();
  }//GEN-LAST:event_jSlider1StateChanged
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JSlider jSlider1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JSlider jSlider2;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  // End of variables declaration//GEN-END:variables
  
  private void writeAgentControls()
  {
      try
      {
          FileWriter file = new FileWriter( out_filename );
          
          file.write( jTextField1.getText() );
          file.write( '\n' );
          file.write( jTextField2.getText() );
          
          file.close();
      }
      catch( Exception e )
      {
          e.printStackTrace();
          System.exit(0);
      }
  }
  
  private void readAgentInfo()
  {
      try
      {
          FileReader fr = new FileReader( in_filename );
          BufferedReader reader = new BufferedReader( fr );
          
          jTextField3.setText( reader.readLine() );
          jTextField4.setText( reader.readLine() );
          
          fr.close();
      }
      catch( Exception e )
      {
          // if the files not there, just let it go
      }
  }
}
