# reference: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/alpine-3.10-git/.devcontainer/Dockerfile

########################
FROM alpine:3.10 as base

# need the musl-dev library to get stdio, etc to work
# alpine uses musl not glibc
RUN apk add --no-cache bash tmux vim git
RUN apk add --no-cache make musl-dev valgrind clang
# needed for 'ld' for now
RUN apk add --no-cache gcc
# this makes `man` work for the standard 'C' library
RUN apk add --no-cache man man-pages
RUN apk add --no-cache sudo


###################
FROM base as vscode

# This Dockerfile adds a non-root user with sudo access. Use the "remoteUser"
# property in devcontainer.json to use it. On Linux, the container user's GID/UIDs
# will be updated to match your local UID/GID (when using the dockerFile property).
# See https://aka.ms/vscode-remote/containers/non-root-user for details.
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.
RUN addgroup -g $USER_GID $USERNAME
RUN adduser -S -s /bin/bash -u $USER_UID -G $USERNAME $USERNAME

# [Optional] Add sudo support for the non-root user
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
RUN chmod 0440 /etc/sudoers.d/$USERNAME


####################
FROM vscode as sweep

# add /sweep directory for non-VSCode develoment
RUN mkdir -p /sweep
RUN git clone https://github.com/mkovacina/dotfiles.git 
RUN cd dotfiles && make install-vim 


###################
FROM sweep as shell

# notes
# - bash was not included in the image, contrary to what the alpine sample indicated
